package cn.com.cis.mi.osp.service.healthRcdsService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-02-20T15:52:34.577+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "HealthApp", name = "HealthServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface HealthServiceSoap {

    /**
     * 获取过敏史,遗传史,家族史,特殊情况,慢性病 4家族史 5遗传病 6过敏史 7慢性病 8特殊情况
     */
    @WebMethod(operationName = "GetDetailMedicalRecord", action = "HealthApp/GetDetailMedicalRecord")
    @RequestWrapper(localName = "GetDetailMedicalRecord", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetDetailMedicalRecord")
    @ResponseWrapper(localName = "GetDetailMedicalRecordResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetDetailMedicalRecordResponse")
    @WebResult(name = "GetDetailMedicalRecordResult", targetNamespace = "HealthApp")
    public cn.com.cis.mi.osp.service.healthRcdsService.ComMedicalList getDetailMedicalRecord(
        @WebParam(name = "Identity_No", targetNamespace = "HealthApp")
        java.lang.String identityNo,
        @WebParam(name = "type", targetNamespace = "HealthApp")
        java.lang.String type
    );

    /**
     * 删除就诊记录
     */
    @WebMethod(operationName = "DelDiseaseRecordRecord", action = "HealthApp/DelDiseaseRecordRecord")
    @RequestWrapper(localName = "DelDiseaseRecordRecord", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.DelDiseaseRecordRecord")
    @ResponseWrapper(localName = "DelDiseaseRecordRecordResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.DelDiseaseRecordRecordResponse")
    @WebResult(name = "DelDiseaseRecordRecordResult", targetNamespace = "HealthApp")
    public boolean delDiseaseRecordRecord(
        @WebParam(name = "model", targetNamespace = "HealthApp")
        cn.com.cis.mi.osp.service.healthRcdsService.AppDiseaseRecord model
    );

    /**
     * 保存就诊记录
     */
    @WebMethod(operationName = "SaveRecordHistory", action = "HealthApp/SaveRecordHistory")
    @RequestWrapper(localName = "SaveRecordHistory", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.SaveRecordHistory")
    @ResponseWrapper(localName = "SaveRecordHistoryResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.SaveRecordHistoryResponse")
    @WebResult(name = "SaveRecordHistoryResult", targetNamespace = "HealthApp")
    public boolean saveRecordHistory(
        @WebParam(name = "modelList", targetNamespace = "HealthApp")
        cn.com.cis.mi.osp.service.healthRcdsService.ArrayOfAppRecordHistory modelList
    );

    /**
     * 保存就诊记录,返回主键
     */
    @WebMethod(operationName = "SaveDiseaseRecordRecord", action = "HealthApp/SaveDiseaseRecordRecord")
    @RequestWrapper(localName = "SaveDiseaseRecordRecord", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.SaveDiseaseRecordRecord")
    @ResponseWrapper(localName = "SaveDiseaseRecordRecordResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.SaveDiseaseRecordRecordResponse")
    @WebResult(name = "SaveDiseaseRecordRecordResult", targetNamespace = "HealthApp")
    public java.lang.String saveDiseaseRecordRecord(
        @WebParam(name = "model", targetNamespace = "HealthApp")
        cn.com.cis.mi.osp.service.healthRcdsService.AppDiseaseRecord model
    );

    /**
     * 1.获取首页8大块信息
     */
    @WebMethod(operationName = "GetHomeInfoEntitys", action = "HealthApp/GetHomeInfoEntitys")
    @RequestWrapper(localName = "GetHomeInfoEntitys", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetHomeInfoEntitys")
    @ResponseWrapper(localName = "GetHomeInfoEntitysResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetHomeInfoEntitysResponse")
    @WebResult(name = "GetHomeInfoEntitysResult", targetNamespace = "HealthApp")
    public cn.com.cis.mi.osp.service.healthRcdsService.HomeInfo getHomeInfoEntitys(
        @WebParam(name = "Identity_No", targetNamespace = "HealthApp")
        java.lang.String identityNo
    );

    /**
     * 获取就诊信息列表
     */
    @WebMethod(operationName = "GetMedicalRecords", action = "HealthApp/GetMedicalRecords")
    @RequestWrapper(localName = "GetMedicalRecords", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetMedicalRecords")
    @ResponseWrapper(localName = "GetMedicalRecordsResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetMedicalRecordsResponse")
    @WebResult(name = "GetMedicalRecordsResult", targetNamespace = "HealthApp")
    public cn.com.cis.mi.osp.service.healthRcdsService.MedicalRecordList getMedicalRecords(
        @WebParam(name = "Identity_No", targetNamespace = "HealthApp")
        java.lang.String identityNo
    );

    /**
     * [获取体征部分信息]1代表身高 2 代表体重 3代表体温,4代表心率,5代表血糖,6代表血压
     */
    @WebMethod(operationName = "GetPhysicalSignInfo", action = "HealthApp/GetPhysicalSignInfo")
    @RequestWrapper(localName = "GetPhysicalSignInfo", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetPhysicalSignInfo")
    @ResponseWrapper(localName = "GetPhysicalSignInfoResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetPhysicalSignInfoResponse")
    @WebResult(name = "GetPhysicalSignInfoResult", targetNamespace = "HealthApp")
    public cn.com.cis.mi.osp.service.healthRcdsService.ComBodyContentList getPhysicalSignInfo(
        @WebParam(name = "Identity_No", targetNamespace = "HealthApp")
        java.lang.String identityNo,
        @WebParam(name = "type", targetNamespace = "HealthApp")
        java.lang.String type
    );

    /**
     * 获取体征信息分页显示
     */
    @WebMethod(operationName = "GetPhrPhysicalSignList", action = "HealthApp/GetPhrPhysicalSignList")
    @RequestWrapper(localName = "GetPhrPhysicalSignList", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetPhrPhysicalSignList")
    @ResponseWrapper(localName = "GetPhrPhysicalSignListResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetPhrPhysicalSignListResponse")
    @WebResult(name = "GetPhrPhysicalSignListResult", targetNamespace = "HealthApp")
    public cn.com.cis.mi.osp.service.healthRcdsService.ArrayOfPhrPhysicalSign getPhrPhysicalSignList(
        @WebParam(name = "Identity_No", targetNamespace = "HealthApp")
        java.lang.String identityNo,
        @WebParam(name = "pageIndex", targetNamespace = "HealthApp")
        int pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "HealthApp")
        int pageSize
    );

    /**
     * 根据主键获取就诊记录详细
     */
    @WebMethod(operationName = "GetClinicRecordByID", action = "HealthApp/GetClinicRecordByID")
    @RequestWrapper(localName = "GetClinicRecordByID", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetClinicRecordByID")
    @ResponseWrapper(localName = "GetClinicRecordByIDResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetClinicRecordByIDResponse")
    @WebResult(name = "GetClinicRecordByIDResult", targetNamespace = "HealthApp")
    public cn.com.cis.mi.osp.service.healthRcdsService.ClinicRecord getClinicRecordByID(
        @WebParam(name = "id", targetNamespace = "HealthApp")
        java.lang.String id
    );

    /**
     * [保存体征信息]1代表身高 2 代表体重 3代表体温,4代表心率,5代表血糖,6代表血压,7代表血型
     */
    @WebMethod(operationName = "SavePhysicalSignInfo", action = "HealthApp/SavePhysicalSignInfo")
    @RequestWrapper(localName = "SavePhysicalSignInfo", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.SavePhysicalSignInfo")
    @ResponseWrapper(localName = "SavePhysicalSignInfoResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.SavePhysicalSignInfoResponse")
    @WebResult(name = "SavePhysicalSignInfoResult", targetNamespace = "HealthApp")
    public boolean savePhysicalSignInfo(
        @WebParam(name = "model", targetNamespace = "HealthApp")
        cn.com.cis.mi.osp.service.healthRcdsService.PhysicalSign model,
        @WebParam(name = "type", targetNamespace = "HealthApp")
        java.lang.String type
    );

    /**
     * 根据id 和类型 获取手术,检查,用药详细 1代表药品 2代表检查 3 代表手术
     */
    @WebMethod(operationName = "GetDiagnosisListsByID", action = "HealthApp/GetDiagnosisListsByID")
    @RequestWrapper(localName = "GetDiagnosisListsByID", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetDiagnosisListsByID")
    @ResponseWrapper(localName = "GetDiagnosisListsByIDResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.GetDiagnosisListsByIDResponse")
    @WebResult(name = "GetDiagnosisListsByIDResult", targetNamespace = "HealthApp")
    public cn.com.cis.mi.osp.service.healthRcdsService.DiagnosisList getDiagnosisListsByID(
        @WebParam(name = "id", targetNamespace = "HealthApp")
        java.lang.String id,
        @WebParam(name = "type", targetNamespace = "HealthApp")
        java.lang.String type
    );

    /**
     * [删除体征信息]
     */
    @WebMethod(operationName = "DelPhysicalSignInfo", action = "HealthApp/DelPhysicalSignInfo")
    @RequestWrapper(localName = "DelPhysicalSignInfo", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.DelPhysicalSignInfo")
    @ResponseWrapper(localName = "DelPhysicalSignInfoResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.DelPhysicalSignInfoResponse")
    @WebResult(name = "DelPhysicalSignInfoResult", targetNamespace = "HealthApp")
    public boolean delPhysicalSignInfo(
        @WebParam(name = "id", targetNamespace = "HealthApp")
        java.lang.String id
    );

    /**
     * [用户身份信息认证接口]
     */
    @WebMethod(operationName = "Identification", action = "HealthApp/Identification")
    @RequestWrapper(localName = "Identification", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.Identification")
    @ResponseWrapper(localName = "IdentificationResponse", targetNamespace = "HealthApp", className = "cn.com.cis.mi.osp.service.healthRcdsService.IdentificationResponse")
    @WebResult(name = "IdentificationResult", targetNamespace = "HealthApp")
    public java.lang.String identification(
        @WebParam(name = "UserId", targetNamespace = "HealthApp")
        java.lang.String userId,
        @WebParam(name = "Identity_No", targetNamespace = "HealthApp")
        java.lang.String identityNo
    );
}
